CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities
(id INT UNIQUE AUTO_GENERATED NOT NULL,
state_id INT NOT NULL FOREIGN KEY REFERENCES hbtn_0d_usa.state(id),
PRIMARY KEY(id)
);
